{
 "title": "Демографический анализ",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Распределение клиентов по возрасту",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT age, COUNT(*) AS \"Кол-во\"\nFROM clients\nGROUP BY age\nORDER BY age;\n"
    }
   ]
  },
  {
   "title": "Распределение клиентов по полу",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT gender, COUNT(*) AS \"Количество клиентов\"\nFROM clients\nGROUP BY gender;\n"
    }
   ]
  },
  {
   "title": "Топ по локациям проживания",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT location, COUNT(*) AS count\nFROM clients\nGROUP BY location\nORDER BY count DESC;\n"
    }
   ]
  },
  {
   "title": "Возраст клиентов",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n  CASE \n    WHEN age < 20 THEN '<20'\n    WHEN age BETWEEN 20 AND 29 THEN '20-29'\n    WHEN age BETWEEN 30 AND 39 THEN '30-39'\n    WHEN age BETWEEN 40 AND 49 THEN '40-49'\n    ELSE '50+' \n  END AS \"Возрастная группа\",\n  COUNT(*) AS \"Кол-во\"\nFROM clients\nGROUP BY \"Возрастная группа\"\nORDER BY \"Возрастная группа\";\n"
    }
   ]
  }
 ]
}