{
 "title": "Общая сводка (KPI)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Общее число рекламодателей",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_advertisers\nFROM advertisers;\n"
    }
   ]
  },
  {
   "title": "Общее число клиентов",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_clients\nFROM clients;\n"
    }
   ]
  },
  {
   "title": "Общее число кампаний",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_campaigns\nFROM campaigns;\n"
    }
   ]
  },
  {
   "title": "Средний CPC кампаний",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    ROUND(\n      SUM(CASE WHEN ae.event_type = 'CLICK' THEN c.cost_per_click ELSE 0 END)::numeric / \n      NULLIF(SUM(CASE WHEN ae.event_type = 'CLICK' THEN 1 ELSE 0 END), 0),\n    4) AS avg_cpc\nFROM ad_events ae\nJOIN campaigns c ON ae.campaign_id = c.campaign_id;\n"
    }
   ]
  },
  {
   "title": "Общее число событий",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS total_events\nFROM ad_events;\n"
    }
   ]
  },
  {
   "title": "Средний CTR кампаний",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    ROUND(\n      SUM(CASE WHEN ae.event_type = 'CLICK' THEN 1 ELSE 0 END)::numeric / \n      NULLIF(SUM(CASE WHEN ae.event_type = 'IMPRESSION' THEN 1 ELSE 0 END), 0),\n    4) AS avg_ctr\nFROM ad_events ae;\n"
    }
   ]
  },
  {
   "title": "Средний CPM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    ROUND(\n      ((SUM(CASE WHEN ae.event_type = 'IMPRESSION' THEN c.cost_per_impression ELSE 0 END) * 1000) / \n      NULLIF(SUM(CASE WHEN ae.event_type = 'IMPRESSION' THEN 1 ELSE 0 END), 0))::numeric, \n    2) AS avg_cpm\nFROM ad_events ae\nJOIN campaigns c ON ae.campaign_id = c.campaign_id;\n"
    }
   ]
  }
 ]
}